#!/bin/bash
#runhaskell -isrc -itest -fforce-recomp test/Spec.hs

ghc -isrc -itest/UnitTests -fhpc test/UnitTests/UnitSpec.hs --make
./test/UnitTests/UnitSpec
#mv UnitSpec.tix test/UnitTests/

ghc -isrc -itest/Programs -fhpc test/Programs/ProgSpec.hs --make
./test/Programs/ProgSpec

hpc sum UnitSpec.tix ProgSpec.tix --output=Specs.tix --exclude=Main --union

hpc report Specs --exclude=Parse.TestParserInvalidSpec
hpc markup Specs --exclude=Parse.TestParserInvalidSpec --destdir=test/outputs


#hpc report test/UnitTests/UnitSpec --exclude=Parse.TestParserInvalidSpec --exclude=QC
#hpc markup test/UnitTests/UnitSpec --exclude=Parse.TestParserInvalidSpec --exclude=QC --destdir=test/outputs

