#!/bin/bash
#runhaskell -isrc -itest -fforce-recomp test/Spec.hs

ghc -isrc -itest/UnitTests -fhpc test/UnitTests/UnitSpec.hs --make
./test/UnitTests/UnitSpec
#mv UnitSpec.tix test/UnitTests/

ghc -isrc -itest/Programs -fhpc test/Programs/ProgSpec.hs --make
./test/Programs/ProgSpec

hpc sum UnitSpec.tix ProgSpec.tix --output=Specs.tix --exclude=Main --union

hpc report --srcdir=src/ --hpcdir=../.hpc Specs
#hpc markup --srcdir=src/ --hpcdir=../.hpc --destdir=test/outputs Specs

#hpc report Specs --exclude=Parse.TestParserInvalidSpec --exclude=Parse.TestParserValidSpec --exclude=Syntax.TestEqInvalidSpec --exclude=Syntax.TestEqTypeSchemeSpec --exclude=Syntax.TestEqValidSpec --exclude=Syntax.TestShowValidSpec --exclude=Validation.TestEquivalenceInvalidSpec --exclude=Validation.TestEquivalenceValidSpec --exclude=Validation.TestKindingInvalidSpec --exclude=Validation.TestKindingValidSpec --exclude=Validation.TestTypeSchemeKindingSpec --exclude=SpecHelper 
hpc markup Specs --exclude=Parse.TestParserInvalidSpec --exclude=Parse.TestParserValidSpec --exclude=Syntax.TestEqInvalidSpec --exclude=Syntax.TestEqTypeSchemeSpec --exclude=Syntax.TestEqValidSpec --exclude=Syntax.TestShowValidSpec --exclude=Validation.TestEquivalenceInvalidSpec --exclude=Validation.TestEquivalenceValidSpec --exclude=Validation.TestKindingInvalidSpec --exclude=Validation.TestKindingValidSpec --exclude=Validation.TestTypeSchemeKindingSpec --destdir=test/outputs --exclude=SpecHelper  --exclude=CompilerSpec --exclude=Syntax.TestTermsEqSpec



#hpc report test/UnitTests/UnitSpec --exclude=Parse.TestParserInvalidSpec --exclude=QC
#hpc markup test/UnitTests/UnitSpec --exclude=Parse.TestParserInvalidSpec --exclude=QC --destdir=test/outputs

