name:                FreeST
version:             0.1.0.0
#github:              "githubuser/ContextFreeSession"
license:             BSD3
author:              "Bernardo Almeida, Vasco T. Vasconcelos, Andreia Mordido"
copyright:           "2019 authors"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ContextFreeSession#readme>

dependencies:
- base >= 4.7 && < 5
- array <= 0.5.3.0
- cond >= 0.4.1.1
- containers >=0.5.9
- directory >= 1.3.2.0
- filepath >= 1.4.2
- mtl >= 2.2.1
- pretty-terminal >= 0.1.0.0
- process <= 1.6.5.0
- silently >= 1.2.5.1
- transformers >= 0.5.6.2

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  exposed-modules:
  # - Main
    - Compiler
    - Equivalence.Grammar
    - Equivalence.Bisimulation
    - Equivalence.Equivalence
    - Equivalence.Normalisation
    - Syntax.TypeVariables
    - Syntax.Base
    - Syntax.Types
    - Syntax.Show
    - Syntax.Expressions
    - Syntax.Schemes
    - Syntax.Kinds
    - Syntax.ProgramVariables
    - Syntax.Duality
    - Parse.ParseUtils
    - Utils.Errors
    - Utils.FreestState
    - Parse.Lexer 
    - Parse.Parser
    - Validation.Rename
    - Validation.Kinding
    - Validation.Contractive    
    - Validation.Substitution

executables:
  freest:
    main:                Main.hs
    source-dirs:         src
    build-tools:
      - alex
      - happy
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
    units:
      main: UnitSpec.hs
      source-dirs: 
        - test/UnitTests
      dependencies:
        - FreeST
        - hspec 
        - hspec-expectations
        - split

    programs:
      main: ProgSpec.hs
      source-dirs: 
        - test/Programs
      dependencies:
        - FreeST
        - hspec       
        - HUnit
        - silently

    valid-types-quick:
      main: QuickCheckSpec.hs
      source-dirs:
        - test/QuickCheck
      dependencies:
        - FreeST
        - QuickCheck
        - hspec
