name:                REPL
version:             1.0.0
license:             BSD3
author:              "Bernardo Almeida"
copyright:           "2022 authors"

# dependencies:
#   - base >= 4.7 && < 5

executables:
  freesti:
    main:                REPL.hs
    source-dirs:         src
    ghc-options: -main-is REPL -threaded -rtsopts -with-rtsopts=-N
    dependencies: 
      - FreeST
      - base >= 4.7 && < 5    
      - mtl >= 2.2.1
      - containers >=0.5.9
      - directory >= 1.3.2.0
      - filepath >= 1.4.2
      - optparse-applicative >= 0.16.1.0
      - control-bool >= 0.2.1
      - extra >= 1.7.9
      - haskeline