module Main where

import Equivalence.Bisimulation
import Parse.GrammarParser
import Equivalence.Grammar
import System.Environment (getArgs)
import           Prelude hiding (Word) -- Word is (re)defined in module Equivalence.Grammar


main :: IO ()
main = do
  -- args <- getArgs
  -- f <- readFile (head args)
  contents <- getContents
  let g = parseGrammar contents
  isBisimGrammar g

isBisimGrammar :: Grammar -> IO ()
isBisimGrammar g@(Grammar [xs, ys] _)
  | bisimilarGrammar g =
      putStrLn $ "The languages generated by " ++ showWord xs ++
                 " and " ++ showWord ys ++ " are bisimilar"
  | otherwise          =    
      putStrLn $ "The languages generated by " ++ showWord xs ++
                 " and " ++ showWord ys ++ " are *not* bisimilar"


showWord :: Word -> String
showWord xs = concat $ map show xs
