name:                Monitor
version:             1.0.0
license:             BSD3
author:              "João Magalhães"
copyright:           "2025 authors"

executables:
  monitor:
    main:                Monitor.hs
    source-dirs:         src
    ghc-options: -main-is Monitor -threaded
    dependencies: 
      - FreeST
      - base >= 4.7 && < 5    
      - mtl >= 2.2.1
      - containers >=0.5.9
      - directory >= 1.3.2.0
      - extra >= 1.7.9
      - bytestring >= 0.10.12.0
      - binary >= 0.8.8.0
      - network