paper48.zip: main.tex biblio.bib main.bbl macros.tex intro.tex examples.tex types.tex processes.tex related.tex conclusion.tex
	zip paper48 main.tex biblio.bib main.bbl macros.tex intro.tex examples.tex types.tex processes.tex related.tex conclusion.tex
