name:                FreeST
version:             1.0.2
#github:              "githubuser/ContextFreeSession"
license:             BSD3
author:              "Bernardo Almeida, Andreia Mordido, Vasco T. Vasconcelos"
copyright:           "2020 authors"

#extra-source-files:
#- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- containers >=0.5.9
- mtl >= 2.2.1
- array <= 0.5.3.0
- directory >= 1.3.2.0
- filepath >= 1.4.2
- process <= 1.6.5.0
# - silently >= 1.2.5.1
# - synchronous-channels >= 0.2

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  exposed-modules:
    - FreeST
    - Bisimulation.Grammar
    - Bisimulation.Bisimulation
    - Equivalence.Equivalence
    - Equivalence.Normalisation
    - Syntax.TypeVariables
    - Syntax.Base
    - Syntax.Type
    - Syntax.Expression
    - Syntax.Schemes
    - Syntax.Kind
    - Syntax.ProgramVariables
    - Parse.ParseUtils
    - Parse.Read
    - Parse.Unparser
    - Utils.Errors
    - Utils.FreestState
    - Parse.Lexer 
    - Parse.Parser
    - Validation.Duality
    - Validation.Terminated
    - Validation.Contractive
    - Validation.Rename
    - Validation.Kinding
    - Validation.Substitution
    - Validation.Typing

executables:
  freest:
    main:                FreeST.hs
    source-dirs:         src
    build-tools:
      - alex
      - happy
    ghc-options: -main-is FreeST

tests:
    units:
      main: UnitSpec.hs
      source-dirs: 
        - test/UnitTests
      dependencies:
        - FreeST
        - hspec 
        - hspec-expectations
        - split

    programs:
      main: ProgSpec.hs
      source-dirs: 
        - test/Programs
      dependencies:
        - FreeST
        - hspec       
        - HUnit
        - silently

    valid-types-quick:
      main: QuickCheckSpec.hs
      source-dirs:
        - test/QuickCheck
      dependencies:
        - FreeST
        - QuickCheck
        - hspec
