name:                FreeST
version:             1.0.2
#github:              "githubuser/ContextFreeSession"
license:             BSD3
author:              "Bernardo Almeida, Andreia Mordido, Vasco T. Vasconcelos"
copyright:           "2020 authors"

#extra-source-files:
#- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- containers >=0.5.9
# - unordered-containers >= 0.2
- mtl >= 2.2.1
- array <= 0.5.3.0
- directory >= 1.3.2.0
- filepath >= 1.4.2
- process <= 1.6.5.0
# - silently >= 1.2.5.1
# - synchronous-channels >= 0.2

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  exposed-modules:
    - FreeST
    - Bisimulation.Grammar
    - Bisimulation.Bisimulation
    - Elaboration.Duality
    - Elaboration.Elaboration
    - Equivalence.Equivalence
    - Equivalence.Normalisation
    - Syntax.TypeVariable
    - Syntax.Base
    - Syntax.Type
    - Syntax.Expression
    - Syntax.Kind
    - Syntax.ProgramVariable
    - Parse.ParseUtils
    - Parse.Read
    - Parse.Unparser
    - Util.Error
    - Util.FreestState
    - Util.PreludeLoader
    - Parse.Lexer 
    - Parse.Parser
    - Validation.Subkind
    - Validation.Terminated
    - Validation.Contractive
    - Validation.Rename
    - Validation.Kinding
    - Validation.Substitution
    - Validation.Typing

executables:
  freest:
    main:                FreeST.hs
    source-dirs:         src
    build-tools:
      - alex
      - happy
    ghc-options: -main-is FreeST -threaded -rtsopts -with-rtsopts=-N

tests:
    units:
      main: UnitSpec.hs
      source-dirs: 
        - test/UnitTests
      dependencies:
        - FreeST
        - hspec >= 2.7.1
        - hspec-expectations >= 0.8.2
        - hspec-discover >= 2.7.1
        - split >= 0.2.3.3

    programs:
      main: ProgSpec.hs
      source-dirs: 
        - test/Programs
      dependencies:
        - FreeST 
        - hspec >= 2.7.1       
        - HUnit >= 1.6.0.0
        - silently >= 1.2.5.1
      ghc-options: -threaded +RTS -N -RTS

    valid-types-quick:
      main: QuickCheckSpec.hs
      source-dirs:
        - test/QuickCheck
      dependencies:
        - FreeST
        - QuickCheck
        - hspec
